### ISSUE TITLE
Component not updating when data changes.

### ISSUE THREAD

**Issue by ardian-c** [sandi-racy/vue-awesomplete#1]
Hi, 

Thank you for this helpful VueJs component. I'm using it on one of my projects, however I'm getting a weird behavior.  
So, I need to get the data for cities in USA or Canada, depending on a radio button. My cities are on a static json file, containing two fields "USA" and "CAN", with an array of cities. On my application I'm using Vuex for managing the state. I can get it to work when component is mounted by retrieving the data for current country, however when changing the country, although `setting: { list: cities }` properties it shows updated array of data, the component still uses older (probably cached) data. Is there a way component to handle this issue?

**Comment by sandi-racy** [comment]
Hi,

Thank you for using this component.

Have you tried using `this.$refs.skills.list(['Angular', 'React', 'Vue'])` ?

**Comment by ardian-c** [comment]
Hi,

Thanks I did forget to add update that. It works correctly now 👍
