### ISSUE TITLE
Key presses

### ISSUE THREAD

**Issue by SimplyCorey** [sandi-racy/vue-awesomplete#2]
Would it be possible to add a keypress event to this component?  I would like to listen to when the "enter" key is pressed.

**Comment by sandi-racy** [comment]
What if you use `selectcomplete` event?

**Comment by SimplyCorey** [comment]
This is for a data input that isnt part of the auto complete.  I was able to get it working by forking it and adding the event.  Would you like for me to make a PR?

**Comment by sandi-racy** [comment]
Yes, please.

**Comment by sandi-racy** [comment]
Closed due to inactivity
